import Navbar from "@/components/Navbar.jsx";
import ThemeProvider from "@/app/providers/ThemeProvider";
import CartProvider from "@/app/providers/CartProvider";
import styles from "@/app/styles/rootLayout.module.css";
import options from "@/app/api/auth/[...nextauth]/authOptions";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);
  console.log({ session });

  return (
    <ThemeProvider themeColors={session?.themeColor}>
      <CartProvider>
        <div className={styles.rootLayout}>
          <Navbar />
          {children}
        </div>
      </CartProvider>
    </ThemeProvider>
  );
}
