import Navbar from "@/__components/Navbar.jsx";
import styles from "@/app/styles/rootLayout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={styles.rootLayout}>
      <Navbar />
      {children}
    </div>
  );
}
